---
  - name: clickhouse-role
    src: https://github.com/duq3r/clickhouse-role.git
    scm: git
    version: "v1"
  - name: vector-role
    src: https://github.com/duq3r/vector-role.git
    scm: git
    version: "v1"
  - name: lighthouse-role
    src: https://github.com/duq3r/lighthouse-role.git
    scm: git
    version: "v1"
  - name: clickhouse-role-Alexey
    src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse